import 'package:flutter/material.dart';
import 'package:flutter_color_changer/app/app_controller.dart';

class App extends StatefulWidget {
  App({super.key});

  @override
  State<App> createState() => _AppState();
}

class _AppState extends State<App> with TickerProviderStateMixin {
  final AppController _controller = AppController();

  @override
  void initState() {
    _controller.registerSetState(() {
      setState(_controller.generateColor);
    });
    _controller.animationController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 400),
    )..addListener(() {
        setState(() {});
      });
    super.initState();
  }

  @override
  void dispose() {
    _controller.colorChangeTimer.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Cool Color Change',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Scaffold(
        bottomNavigationBar: AnimatedContainer(
          color: _controller.currentColor,
          duration: const Duration(milliseconds: 400),
          child: SizedBox(
            height: 30,
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text(
                  _controller.rgbValue,
                  style: TextStyle(
                    color: _controller.contrastTextColor.withAlpha(100),
                    fontSize: 10,
                  ),
                ),
                const Padding(
                  padding: EdgeInsets.symmetric(vertical: 5),
                  child: VerticalDivider(),
                ),
                Text(
                  "Auto Change",
                  style: TextStyle(
                    color: _controller.contrastTextColor.withAlpha(100),
                    fontSize: 10,
                  ),
                ),
                Transform.scale(
                  scale: 0.5,
                  child: Switch(
                    value: _controller.autoGenerated,
                    onChanged: (v) {
                      setState(_controller.setAutoGenerate);
                    },
                  ),
                ),
              ],
            ),
          ),
        ),
        body: GestureDetector(
          onTapDown: (details) {
            setState(() {});
            _controller.startClickEffect(details.localPosition);
          },
          child: Stack(
            children: [
              AnimatedContainer(
                color: _controller.currentColor,
                duration: const Duration(milliseconds: 400),
                child: Center(
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Text(
                        "H e l l o   T h e r e",
                        style: TextStyle(
                          color: _controller.contrastTextColor,
                          fontSize: 24,
                        ),
                      ),
                    ],
                  ),
                ),
              ),

              if (_controller.showEffect && _controller.clickPosition != null)
                Positioned(
                  left: _controller.clickPosition!.dx - 5,
                  top: _controller.clickPosition!.dy - 5,
                  child: AnimatedBuilder(
                    animation: _controller.animationController,
                    builder: (context, child) {
                      return Container(
                        width: 60 * _controller.animationController.value,
                        height: 60 * _controller.animationController.value,
                        decoration: BoxDecoration(
                          shape: BoxShape.circle,
                          color: _controller.currentColor.withValues(
                            alpha: 1.0 - _controller.animationController.value,
                          ),
                        ),
                      );
                    },
                  ),
                ),
            ],
          ),
        ),
      ),
    );
  }
}
