import 'package:flutter/material.dart';
import 'package:flutter_color_changer/app/app_controller.dart';

class App extends StatefulWidget {
  App({super.key});

  @override
  State<App> createState() => _AppState();
}

class _AppState extends State<App> {
  final AppController _controller = AppController();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Cool Color Change',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Scaffold(
        bottomNavigationBar: AnimatedContainer(
          color: _controller.currentColor,
          duration: const Duration(milliseconds: 400),
          child: SizedBox(
            height: 30,
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text(
                  _controller.rgbValue,
                  style: TextStyle(
                    color: _controller.contrastTextColor.withAlpha(100),
                    fontSize: 10,
                  ),
                ),
                const Padding(
                  padding: EdgeInsets.symmetric(vertical: 5),
                  child: VerticalDivider(),
                ),
                Text(
                  "Auto Change",
                  style: TextStyle(
                    color: _controller.contrastTextColor.withAlpha(100),
                    fontSize: 10,
                  ),
                ),
                Transform.scale(
                  scale: 0.5,
                  child: Switch(
                    value: _controller.autoGenerated,
                    onChanged: (v) {
                      setState(_controller.setAutoGenerate);
                    },
                  ),
                ),
              ],
            ),
          ),
        ),
        body: GestureDetector(
          onTapDown: (details) => setState(_controller.generateColor),
          child: AnimatedContainer(
            color: _controller.currentColor,
            duration: const Duration(milliseconds: 400),
            child: Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Text(
                    "H e l l o   T h e r e",
                    style: TextStyle(
                      color: _controller.contrastTextColor,
                      fontSize: 24,
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
