import 'dart:async';
import 'dart:math';
import 'package:flutter/material.dart';

class AppController {
  Color currentColor = Colors.white;
  bool autoGenerated = false;
  late Timer colorChangeTimer;

  late VoidCallback _onChange;

  void registerSetState(VoidCallback onChange) => _onChange = onChange;

  setAutoGenerate() {
    autoGenerated = !autoGenerated;

    if (autoGenerated) {
      colorChangeTimer = Timer.periodic(const Duration(seconds: 4), (timer) {
        _onChange();
      });
    } else {
      colorChangeTimer.cancel();
    }
  }

  void generateColor() {
    final red = Random().nextInt(256);
    final blue = Random().nextInt(256);
    final green = Random().nextInt(256);
    currentColor = Color.fromRGBO(red, blue, green, 1);
  }

  Color get contrastTextColor {
    final luminance = currentColor.computeLuminance();
    return luminance > 0.5 ? Colors.black : Colors.white;
  }

  String get rgbValue {
    final String red = currentColor.r.toStringAsFixed(3);
    final String green = currentColor.g.toStringAsFixed(3);
    final String blue = currentColor.b.toStringAsFixed(3);
    return 'Red:$red, Green: $green,Blue: $blue';
  }
}
